/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.Jogo;
import controle.Plataforma;
import entidade.ManterJogo;
import entidade.ManterPlataforma;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author joao.souza
 */
public class FormAlterarJogo extends javax.swing.JFrame {

    /**
     * Creates new form FormAlterarAluno
     */
    public FormAlterarJogo() {
        initComponents();
        loadComboBoxData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTpesquisar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jTempresa = new javax.swing.JTextField();
        jBpesquisar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTgenero = new javax.swing.JTextField();
        jCplataformas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Digite o codigo do Jogo a ser Alterado:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Empresa:");

        jBpesquisar.setText("Pesquisar");
        jBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarActionPerformed(evt);
            }
        });

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Genero:");

        jCplataformas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jBpesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCplataformas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTnome, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addComponent(jTempresa)
                                .addComponent(jTgenero)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCplataformas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBpesquisar)
                    .addComponent(jButton1))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarActionPerformed
        // TODO add your handling code here:
        Jogo a = new Jogo();
        try{
        
            ManterJogo dao = new ManterJogo();        
            a.setID(Integer.parseInt(jTpesquisar.getText())); 
            dao.PesquisarRegistro(a);
            //JOptionPane.showMessageDialog(null, a.getNome());
        
            jTnome.setText(a.getNome());
            jTempresa.setText(a.getEmpresa());   
            jTgenero.setText(a.getGenero());

            // Find the index of the selected Plataforma in the ArrayList
            ManterPlataforma plataformaDAO = new ManterPlataforma();
            ArrayList<Plataforma> plataformas = plataformaDAO.PesquisarPlataformas();
            int selectedIndex = -1;

            for (int i = 0; i < plataformas.size(); i++) {
                Plataforma plataforma = plataformas.get(i);
                if (plataforma.getID() == a.getPlataforma_id()) {
                    jCplataformas.setSelectedIndex(i);
                    break;
                }
            }

            // Set the selected index for the JComboBox
            if (selectedIndex != -1) {
                jCplataformas.setSelectedIndex(selectedIndex);
            }                
                 
      } 
      catch (Exception e){
            System.out.println("Erro " + e.getMessage());
       }
    }//GEN-LAST:event_jBpesquisarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
        Jogo a = new  Jogo();
            ManterJogo dao = new ManterJogo();
            a.setID(Integer.valueOf(jTpesquisar.getText()));
            a.setNome(jTnome.getText());
            a.setEmpresa(jTempresa.getText());
            a.setGenero(jTgenero.getText());
            
            String selectedPlataformaNome = (String) jCplataformas.getSelectedItem();

            // Find the corresponding Plataforma object in the list
            ManterPlataforma plataformaDAO = new ManterPlataforma();
            ArrayList<Plataforma> plataformas = plataformaDAO.PesquisarPlataformas();
            Plataforma selectedPlataforma = null;

            for (Plataforma plataforma : plataformas) {
                if (plataforma.getNome().equals(selectedPlataformaNome)) {
                    selectedPlataforma = plataforma;
                    break;
                }
            }

            // Set the plataforma_id in the Jogo object
            if (selectedPlataforma != null) {
                a.setPlataforma_id(selectedPlataforma.getID());
            } else {
                // Handle the case where the selectedPlataforma is null (optional)
                System.out.println("Plataforma not found for: " + selectedPlataformaNome);
            }
            dao.editarJogo(a); 
      
            jTnome.setText("");
            jTempresa.setText("");
            jTgenero.setText(" ");
            jTpesquisar.setText("");
            jTpesquisar.requestFocus();
      }catch(Exception e){
        JOptionPane.showMessageDialog(this,"Erro de : " + e.getMessage());
      }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void loadComboBoxData() {
        try {
            ManterPlataforma dao = new ManterPlataforma();
            // Assuming PesquisarTudo is a method in your database access class
            // Modify this according to your actual class structure
            ArrayList<Plataforma> plataformas = dao.PesquisarPlataformas();

            // Clear existing items in the combo box
            jCplataformas.removeAllItems();

            // Add the 'nome' values to the combo box
            for (Plataforma plataforma : plataformas) {
                jCplataformas.addItem(plataforma.getNome());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAlterarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAlterarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAlterarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAlterarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAlterarJogo().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBpesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCplataformas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTempresa;
    private javax.swing.JTextField jTgenero;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTpesquisar;
    // End of variables declaration//GEN-END:variables
}
